### ISSUE TITLE
Using Electron

### ISSUE THREAD

**Issue by R4356th** [SnapForks/SnapSporks#1]
I see there is a package.json file. Are you going to use Electron for making this app?

**Comment by Daniel4-Scratch** [comment]
Whats that?

**Comment by R4356th** [comment]
It is a framework for building cross-platform applications with web technologies. You can read about it here- https://www.electronjs.org/.

**Comment by Daniel4-Scratch** [comment]
Thanks i'll see what i can do.

**Comment by Daniel4-Scratch** [comment]
I'm confused how do I download the editor app? I got a demo app instead of a editor.

**Comment by Daniel4-Scratch** [comment]
I'm confused how to use electron.

**Comment by R4356th** [comment]
Hey, relax. I was just curious to know if you had any plan of using Electron or Node.JS (which requires a package.json file); you may also use HTML as well.

**Comment by Daniel4-Scratch** [comment]
Do i seem angry? I'm not angry. Package.json is a default name for json files

**Comment by R4356th** [comment]
Nah, you do not seem angry. :)

**Comment by Daniel4-Scratch** [comment]
oh, the way you said relax seemed like for me to calm down.
